### ISSUE TITLE
Tooltip tag has a overflow-y enabled

### ISSUE THREAD

**Issue by GuillQuirin** [muxinc/media-chrome#1000]
Hello, 

Since this [last update](https://github.com/muxinc/media-chrome/pull/994/files), tooltips have a default vertical scroll displayed.
Is it possible to add `overflow-y: hidden` or explain how to apply a specific CSS rule to the Shadow DOM from the media-controller ?

![Image](https://github.com/user-attachments/assets/b624f0e3-6171-4dd1-80dd-fc46dbdc80a5)

Thanks !

**Comment by JeroenReumkens** [comment]
Just made #1002 to fix this as I noticed it too.
