### ISSUE TITLE
media-playback-rate-menu's rates doesn't work  in vue3

### ISSUE THREAD

**Issue by EssLi** [muxinc/media-chrome#1014]
Hi, I'm encountering an issue where some components do not work when integrating the media-chrome elements into a Vue 3 project， code as following：

    <template>
        <div class="HlsjsPlayer">
            <media-controller>
                <hls-video 
                    ref="hlsVideoRef" 
                    crossorigin 
                    playsinline 
                    slot="media" 
                    muted 
                    preload="none"
                    @play="onPlay"
                    @loadedmetadata="onLoadedMetadata"
                    @playing="onPlaying"
                    @error="onError">
                </hls-video>
                <media-loading-indicator 
                    slot="centered-chrome" 
                    noautohide 
                    :class="{ 'visible': showLoadingIndicator, 'hidden': !showLoadingIndicator }">
                </media-loading-indicator>
                <media-control-bar :style="{ display: controlBarDisplay }">
                    <media-play-button></media-play-button>
                    <media-time-range></media-time-range>
                    <media-time-display show-duration></media-time-display>
                    <media-playback-rate-menu-button></media-playback-rate-menu-button>
                    <media-seek-backward-button seekoffset="0.04"  @click="onSeekBackwardClick"></media-seek-backward-button>
                    <media-seek-forward-button seekoffset="0.04" @click="onSeekForwardClick"></media-seek-forward-button>
                    <media-mute-button></media-mute-button>
                    <media-fullscreen-button></media-fullscreen-button>
                </media-control-bar>
                <media-playback-rate-menu rates="8 4 2 1.5 1 0.5 0.25" hidden anchor="auto"></media-playback-rate-menu>
            </media-controller>
       
        </div>
    </template>
the media-playback-rate-menu‘s rates doesn’t work, can you give me some advice?

**Comment by luwes** [comment]
did you import the separate menu import?

https://www.media-chrome.org/docs/en/components/media-playback-rate-menu

```js
import "media-chrome";
import "media-chrome/menu";
```

**Comment by EssLi** [comment]
yes, i import it.
 finally, i had to modify the DEFAULT_RATES value of media-playback-rate-button.ts，it seems the media-playback-rate-menu.ts and media-rendition-menu-button.ts was not loaded correctly.
modified the DEFAULT_RATES value of media-rendition-menu-button.ts is invalid.

**Comment by EssLi** [comment]
i had to modify the DEFAULT_RATES value of media-playback-rate-button.ts but not set rates property for media-playback-rate-menu directly 。if i wanna set other values for it, i have to modify from source code and npm run build again, i think it's a temporary solution.

**Comment by luwes** [comment]
strange, this example with custom rates seems to work 
https://www.media-chrome.org/docs/en/components/media-playback-rate-menu#setting-rates

**Comment by EssLi** [comment]
yeah, maybe it's incompatible with vue3 or  other reasons.  use temporary solutions first。thanks you for reply,
