### ISSUE TITLE
handle video tag click event

### ISSUE THREAD

**Issue by EssLi** [muxinc/media-chrome#1016]
<media-controller>
                <hls-video 
                    ref="hlsVideoRef" 
                    crossorigin 
                    playsinline 
                    slot="media" 
                    muted 
                    preload="none"
                    @play="onPlay"
                    @loadedmetadata="onLoadedMetadata"
                    @playing="onPlaying"
                    @error="onError">
                </hls-video>
               
                <media-control-bar :style="{ display: controlBarDisplay }">
                    <media-play-button></media-play-button>
                    <media-time-range></media-time-range>
                    <media-time-display show-duration></media-time-display>
                    <media-playback-rate-menu-button></media-playback-rate-menu-button>
                    <media-seek-backward-button seekoffset="0.04"  @click="onSeekBackwardClick"></media-seek-backward-button>
                    <media-seek-forward-button seekoffset="0.04" @click="onSeekForwardClick"></media-seek-forward-button>
                    <media-mute-button></media-mute-button>
                    <media-fullscreen-button></media-fullscreen-button>
                </media-control-bar>
                <media-playback-rate-menu rates="8 4 2 1.5 1 0.5 0.25" hidden anchor="auto"></media-playback-rate-menu>
            </media-controller>

i wanna capture the event of hls-video tag and prevent default of click operation, for example
video.addEventListener('click', (event) => {
event.preventDefault();
})

my target is that avoid pause when click the video area but have no effect on media-control-bar.
and i hope that double-click to full-screen or exit full-screen too.
but it seems to be hard to trigger this event and capture it. can you give me advice? thanks.

btw, the media-controller click event is ok.

**Comment by luwes** [comment]
could you try setting this CSS var `--media-gesture-receiver-display` to `none`. I think that should do what you're looking for.

this element handles the click events on the video surface:
https://github.com/muxinc/media-chrome/blob/main/src/js/media-gesture-receiver.ts

**Comment by EssLi** [comment]
You are right, it perfectly solved my problem. Thank you again!
