### ISSUE TITLE
Feature request: make clicks on video area toggle play/pause

### ISSUE THREAD

**Issue by ShaunDychko** [muxinc/media-chrome#117]
Feature request: consider making a click on the video toggle between play/pause. Currently the only way to play/pause the video is by clicking the play/pause button in the control bar.
Tested with `media-chrome@0.4.2` on [codepen](https://codepen.io/checkmark/pen/WNZqPvv).

**Comment by heff** [comment]
@cjpillsbury do we just need to re-add this now that we have a gesture-layer or is there more to it?

**Comment by cjpillsbury** [comment]
I'll have to see if we need to do anything with the pointer-events or similar now that we have layers, but otherwise yeah it should just be a gesture layer add. As a first pass I'll plan on building it as a simple (invisible) component.

**Comment by cjpillsbury** [comment]
fyi this will be more complex for touch screens where touches will often be used to show/hide controls

**Comment by luwes** [comment]
It would be nice to keep the right-click menu options of the video element. Will these be removed with a new gesture layer on top? Picture in picture and Chromecasting is always nice to have without needing special buttons.

![SCR-20220124-oin](https://user-images.githubusercontent.com/360826/150883654-1f7f4c7e-1b05-422e-97fd-9077b9414b44.png)

**Comment by cjpillsbury** [comment]
Good callout @luwes I'd agree we should make sure we're not loosing that if at all possible in the implementation.

**Comment by luwes** [comment]
This was added in https://github.com/muxinc/media-chrome/pull/212
