### ISSUE TITLE
New notes tab on Mac covers fullscreen button

### ISSUE THREAD

**Issue by heff** [muxinc/media-chrome#119]
Mac Monterey has a new feature where if you mouse to the bottom right of the screen, a little tab will pop up allowing you to create a new note (Apple Notes). The tab overlaps the default placement of the fullscreen button, creating a not so great experience. I think I was asked if I wanted to turn it on or not, so it might not affect everyone.

It feels like we should care, but interested in opinions on that. I'm not sure what a broad solution to that would look like. It'll be interesting to see what other players do with it.

![image](https://user-images.githubusercontent.com/166/150659022-bcadcbbf-dcc8-4de3-af1e-ed436173e2d3.png)

**Comment by philcluff** [comment]
I don't think we should care, but god this feature is completely ridiculous. I feel like we should at least send a Radar in flagged with accessibility, as it's overlapping common safe screen areas.
 
(Also I'm sure you know, but you can turn this off in the "hot corners" configuration)

**Comment by gkatsev** [comment]
If you enter the corner area more closely the pop-up doesn't show up. So, yeah, can probably be ignored for now. Worth bringing it up with Apple as Phil mentioned.

**Comment by heff** [comment]
Cool, all good points. Maybe it's actually that people will just turn it off after running into this issue enough. 🤞  Definitely an oversight on Apple's part, although their players' controls are usually centered in fullscreen. Closing for now.
