### ISSUE TITLE
Feature Request: made the seek backward/forward time configurable

### ISSUE THREAD

**Issue by ShaunDychko** [muxinc/media-chrome#124]
Please consider making the seek backward/forward time configurable, presumably through an attribute on the element such as in the following:

```html
<media-seek-backward-button amount="10"></media-seek-backward-button>
```

The amount, 30 seconds, is currently hardcoded as a constant used in the line: https://github.com/muxinc/media-chrome/blob/6c6d8576be6c80cf7f0acebf951763fa42dd21db/src/js/media-seek-backward-button.js#L44

The small visible number in the control bar curved arrow would also need to update to reflect the new seek back amount.

**Comment by cjpillsbury** [comment]
Hey @ShaunDychko just a heads up that this is a feature we're planning on working on soon and has a related discussion here: #115
