### ISSUE TITLE
Efficiency of element attribute changes

### ISSUE THREAD

**Issue by luwes** [muxinc/media-chrome#132]
Every time a `setAttribute` is called on a custom element the `attributeChangedCallback` is triggered.
https://codesandbox.io/s/strange-golick-c10fz?file=/src/index.js

Should this be gated in the code below if there was no actual change to the attribute value?
Or should it be handled in the affected custom element itself?

https://github.com/muxinc/media-chrome/blob/f476f82d55dfbd22bc2ee0fcb0cba56107ffca56/src/js/media-controller.js#L508-L520

**Comment by cjpillsbury** [comment]
Also, I 100% hate that `attributeChangedCallback` is invoked based on a `setAttribute()` invocation and not, in fact, based on a changed attribute. 👎

**Comment by cjpillsbury** [comment]
Confirmed on macOS evergreen Safari, Chrome, and Firefox.

**Comment by gkatsev** [comment]
What's the likelihood of folks manually calling `setAttribute()` on elements? If it's high, individual `attributeChangedCallback`s may want to guard against doing work if not necessary.

**Comment by luwes** [comment]
sorry for the late reply

@gkatsev the media controller propagates state to the controls with media-* attributes. 
there could be a case where from a high frequency event like timeupdate or progress the controller keeps on resetting the attribute to the same value triggering the `attributeChangedCallback` for no reason.

indeed I brought it up with the `timeupdate` event and the loading indicator in mind but for now that event is left out. probably safe to leave this until we run into real perf bottlenecks

**Comment by luwes** [comment]
close until real needs arise
