### ISSUE TITLE
fullscreen in vertical video

### ISSUE THREAD

**Issue by netizen-ais** [muxinc/media-chrome#149]
With a portrait oriented video (typical mobile source), the full screen crops to the top section of the video element only.

**Comment by heff** [comment]
Thanks for submitting an issue. Can you provide an example video URL and/or a screen shot of what you're seeing?

With a quick pass of grabbing a vertical video and trying it on the media-chrome.org player, it looks ok.

![image](https://user-images.githubusercontent.com/166/152259561-70023214-f477-47c1-8c97-0c5977506635.png)

**Comment by netizen-ais** [comment]
What I see there is that the controls are outside the video. my <video> element has the same size of the video content, no black empty areas around

**Comment by heff** [comment]
Can you share a screenshot, please?

**Comment by netizen-ais** [comment]
Of course, before/after pressing fullscreen icon:
![20220315100514](https://user-images.githubusercontent.com/3426685/158343870-638789d2-77bd-4185-a330-708c7e1e91d6.jpeg)
![20220315100612](https://user-images.githubusercontent.com/3426685/158343932-4400b167-f076-424a-b2a1-bb392b3016a2.jpeg)

**Comment by tomByrer** [comment]
Tried manually setting the [aspect-ratio](https://github.com/muxinc/media-chrome/blob/main/docs/media-controller.md#styling)?

I could check out if you have your code live somewhere.

**Comment by luwes** [comment]
@netizen-ais did you find a solution in the mean time? 
any chance we could have a look at a test url or some HTML code? that will make it a lot easier to debug. thanks!

**Comment by netizen-ais** [comment]
Sorry, we've deleted that branch, I'm closing this. I think the problem was on my implementation, as no one else reported that. Thank you for the lib and the support

**Comment by NamPNQ** [comment]
I encountered the same problem, and I suspect it might be due to the CSS

```
video {
    max-width: 100%;
    height: auto;
}
```

**Comment by netizen-ais** [comment]
> I encountered the same problem, and I suspect it might be due to the CSS

I can confirm the video element I was trying to manage, has those CSS values
