### ISSUE TITLE
Shouldn't media-controller auto-hide when a video is defined with the "autoplay" attribute?

### ISSUE THREAD

**Issue by alariej** [muxinc/media-chrome#155]
Hi, I am currently testing the library in a WebView on iOS, using the following code:
```
<media-controller autohide="2">
    <video slot="media" autoplay>
        <source src="${ url }" type="${ mimeType }">
    </video>
    <media-control-bar>
        <media-play-button></media-play-button>
        <media-mute-button></media-mute-button>
        <media-time-range></media-time-range>
        <media-duration-display></media-duration-display>
    </media-control-bar>
</media-controller>
```
The problem is that users have to realize, they must touch the video after it starts autoplaying for the autohide attribute to kick in. Wouldn't it be more logical for autohide to be respected without requiring user interaction in this case? In other words: The video start playing automatically, then the controls auto-hide after 2 seconds (autohide="2").

**Comment by cjpillsbury** [comment]
Good callout, @alariej! Reproducible locally. @heff this feels like it's either a bug or a feature request/improvement (I'm leaning bug), but I'd agree this should be accounted for, either along with some of the other auto-hide on touch devices edge cases or as a standalone effort.

**Comment by heff** [comment]
Yeah, bug, but definitely part of the bigger story which includes how we re-introduce tapping on the video itself and the different functionality between desktop and mobile (toggle playback vs. toggle controls).

At first glance what's causing it is related to focus on the play button, preventing controls from hiding. Doesn't seem to be an issue on Safari desktop, so not sure the difference.

**Comment by dylanjha** [comment]
Good find, thanks @alariej !
