### ISSUE TITLE
autohide broken with new poster layer

### ISSUE THREAD

**Issue by gkatsev** [muxinc/media-chrome#187]
Going to https://media-chrome.mux.dev/examples/basic.html, clicking play, and then hovering over the video should auto hide after 2 seconds. However, it does not.
If I set `display:none` n the poster-layer, this behavior is returned.

user-inactive only gets set when mousing out of the player area instead of also after a timeout.

**Comment by gkatsev** [comment]
This is also related to #116 and once this is fixed potentially can close out #116.

**Comment by cjpillsbury** [comment]
Fixed by #191
