### ISSUE TITLE
user inactivity tracking doesn't account for mouse clicks

### ISSUE THREAD

**Issue by gkatsev** [muxinc/media-chrome#188]
In media-container, we set user-inactive after a timer or when we mouse out of the video player and remove it on mouse movement or keyup. For completeness, we should also consider adding `mouseup` or `click` events. As it's possible that the user clicked on the player without moving the mouse since the player was last put into user-inactive mode.

**Comment by cjpillsbury** [comment]
Wrong Issue. PR resolved #187
