### ISSUE TITLE
HTMLElement is not defined in Next.js 12 app

### ISSUE THREAD

**Issue by daletom** [muxinc/media-chrome#210]
Tried adding Media Chrome to a next.js 12 app. Getting a HTMLElement is not defined error.  I copied this from the next demo for Media Chrome.  Is this something I am doing wrong? 
 I Used the following code: 

```
import MediaController from 'media-chrome/dist/react';

export default function Home() {
  return (
    <div>
      <MediaController>
      <video
            slot="media"
            src="https://stream.mux.com/DS00Spx1CV902MCtPj5WknGlR102V5HFkDe/high.mp4"
            preload="auto"
            muted
            crossOrigin=""
          >
          </video>  
      </MediaController>
    </div>
  )
}
```

Getting this error:

Server Error
ReferenceError: HTMLElement is not defined

This error happened while generating the page. Any console logs will be displayed in the terminal window.
Call Stack
eval
node_modules/media-chrome/dist/themes/media-theme.js (1:168)
Object../node_modules/media-chrome/dist/themes/media-theme.js
file:///Users/tom/Documents/GitHub/training/.next/server/pages/index.js (422:1)
__webpack_require__
file:///Users/tom/Documents/GitHub/training/.next/server/webpack-runtime.js (33:42)
eval
webpack-internal:///./node_modules/media-chrome/dist/index.js (59:81)
Object../node_modules/media-chrome/dist/index.js
file:///Users/tom/Documents/GitHub/training/.next/server/pages/index.js (132:1)
__webpack_require__
file:///Users/tom/Documents/GitHub/training/.next/server/webpack-runtime.js (33:42)
eval
webpack-internal:///./node_modules/media-chrome/dist/react/index.js (32:67)
Object../node_modules/media-chrome/dist/react/index.js
file:///Users/tom/Documents/GitHub/training/.next/server/pages/index.js (412:1)
__webpack_require__
file:///Users/tom/Documents/GitHub/training/.next/server/webpack-runtime.js (33:42)
eval
webpack-internal:///./pages/index.js (11:81)

**Comment by cjpillsbury** [comment]
Thanks @daletom looks like a recent feature addition broke our SSR. Should have a fix asap!
