### ISSUE TITLE
error importing react dist into Next.js 12 app

### ISSUE THREAD

**Issue by dylanjha** [muxinc/media-chrome#230]
<img width="1510" alt="nextjs-mc_2022-05-26_06-12-29" src="https://user-images.githubusercontent.com/764988/170494518-3d0e503a-ef7c-4488-b69d-95d5f03b536c.png">

https://codesandbox.io/s/mediachrome-heroicons-react-notu1u

**Comment by gkatsev** [comment]
Related https://github.com/muxinc/media-chrome/pull/231

Relevant piece that isn't in that PR:
> We should also update the react build to generate a cjs subfolder and have a package.json that splits imports between the esm and cjs files. (Also, if we generate it to the root rather than dist, the require/import could be media-chrome/react rather than media-chrome/dist/react

**Comment by dylanjha** [comment]
This is no longer happening, I think it was a CSB bug that got resolved
