### ISSUE TITLE
Custom SVG slots for icons are not working as expected with tailwind

### ISSUE THREAD

**Issue by dylanjha** [muxinc/media-chrome#262]
When using Media Chrome with tailwindcss on the page I noticed some unexpected behavior when using custom icons

Here's a `<media-play-button>` that uses a `slot="play"` and a `slot="pause"`

```html
<media-play-button>
  <svg slot="play" class="w-6 h-6" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zM9.555 7.168A1 1 0 008 8v4a1 1 0 001.555.832l3-2a1 1 0 000-1.664l-3-2z" clip-rule="evenodd"></path></svg>
  <svg slot="pause" class="w-6 h-6" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zM7 8a1 1 0 012 0v4a1 1 0 11-2 0V8zm5-1a1 1 0 00-1 1v4a1 1 0 102 0V8a1 1 0 00-1-1z" clip-rule="evenodd"></path></svg>
</media-play-button>
```

What I noticed is that both the play button and pause button were visible at the same time. Upon some digging I found that both the play and pause SVGs were getting `display: block`.

CSS in the light DOM (tailwind reset) has a rule where it sets `svg { display: block; }` -- this isn't tailwind specific, probably a lot of CSS reset code does this or something similar.

<img width="1486" alt="pause-showing_2022-06-02_09-50-27" src="https://user-images.githubusercontent.com/764988/178347136-9666489f-0afc-4781-a8d0-af1f6284a9c0.png">

Because of specificity, the CSS from light DOM that set `svg { display: block; }` was over-riding the `{ display: none }` set on [the slots by the shadow DOM](https://github.com/muxinc/media-chrome/blob/cec3aaa79980cbd969a90cd0128a31dc70f4b87f/src/js/media-play-button.js#L18-L26)

What's the best way to work-around this?

**Comment by dutchcelt** [comment]
I'd place the `<svg>` in a slot `<div slot="play"><svg></div>`. And then use `::slotted(*)`.

**Comment by dutchcelt** [comment]
All the options suck:
1. Set a style attribute on the SVG: `this.shadowRoot.host.querySelector('[slot=play]').style='display:none';`
2. Create a lightdom style `media-play-button:not([media-paused]) svg[slot=play] { display: none; }`
3. Add `!important` on the `::slotted` style: ` { display: none !important; }

A more involved solution is using the custom property space toggle for option two. This would have the benefit of being useful elsewhere.

You could also create datauri's of the svg's and add them to a custom property on the root and render them in the shadowdom.

**Comment by dylanjha** [comment]
Thanks @dutchcelt ! 

(1) might be the best, honestly.

(2) is a workaround, but not a long-term option cause we don't want to make users of media-chrome do that everywhere.

My thought was (3) but that felt nasty. At least having someone else endorse that as a possible option makes me feel a little better about it 😄

**Comment by cjpillsbury** [comment]
Awesome assist, @dutchcelt . Given those options, I'd also lean towards (1).
Longer term, we can consider something like an "official CSS" that we publish alongside media-chrome that folks can use to avoid these things

**Comment by luwes** [comment]
merci bovenbuur @dutchcelt 👋 

an alternative to setting the style attribute, use the hidden attribute although it might not take priority. 
might need another CSS rule `hidden { display: none !important }`

another thing that comes to mind is using not `display` to do the hiding, can use `visibility` and force the icons to overlay each other with grid or position maybe
https://pqina.nl/blog/css-grid-position-absolute-alternative/

or maybe even removing and adding the slots? would that work 🤔

**Comment by meyerweb** [comment]
@dylanjha Is there a test site or CodePen or similar example of this I could poke at?  I’d like to test some new CSS features that might help here, or at least determine why this use  case isn’t addressed by them for future thinking about new CSS features.

**Comment by dylanjha** [comment]
@meyerweb yep! 😸 

https://codesandbox.io/s/media-chrome-tailwind-ds2tgq

**Comment by meyerweb** [comment]
I didn’t come up with anything new and fancy, but adding this to the web component’s CSS seems to work for me:

```
media-play-button[aria-label="pause"] svg[slot="play"],
media-play-button[aria-label="play"] svg[slot="pause"] {
   display: none;
}
```

The higher specificity of the rule overcomes Tailwind’s reset.

I also kinda disagree with TW’s application of `block` to those elements, and would happily just delete it, but if it’s an automated dependency I can see not wanting to mess around with its code.

**Comment by dutchcelt** [comment]
[luwes](https://github.com/luwes) I agree. You can hide the element in other ways without tripping up over the light dom cascading into the shadow dom... as it stands now. 

Options to play around with: Positioning, z-index, visibility, opacity and `pointer-events: none;`. 

```css
:host(:not([media-paused])) ::slotted([slot='play']){ 
    position: absolute;
    visibility: hidden;
    pointer-events: none;
}
```

This is still a work-a-round for unwanted behaviour by the light dom interfering in the shadow dom. 
A more robust approach to avoid the mess with slots and move the icon out of the dom and into a custom element <i-icon name='play'> and swap out the attribute name or use a CSS custom property for the host background or pseudo-element.

**Comment by dylanjha** [comment]
I think we're pretty aligned on:

- externalizing icons with a custom element `<media-icon>` is ideal [inspiration from Shoelace](https://shoelace.style/components/icon?id=custom-icons)
- to solve this without re-doing how we do icons, `!important` is an acceptable least-bad option [twitter thread with more discussion](https://twitter.com/claviska/status/1547166110851686405)
