### ISSUE TITLE
youtube example doesn't work after refresh

### ISSUE THREAD

**Issue by kasperkamperman** [muxinc/media-chrome#280]
https://media-chrome.mux.dev/examples/media-elements/youtube.html

Tested this in Chrome 103/Safari 15.5 on MacOs 12.4 

On first load it seems to work on both (I tested this in private mode). Doing a refresh, the page is reloaded but all buttons don't work. No start, skip or whatever possible. 

View on first load. 
<img width="746" alt="Screenshot 2022-08-04 at 22 21 53" src="https://user-images.githubusercontent.com/1760616/182945537-ddbdc06c-5453-419e-b042-ba7a7f12e8ec.png">

View after refresh. 
<img width="759" alt="Screenshot 2022-08-04 at 22 22 18" src="https://user-images.githubusercontent.com/1760616/182945553-e0003022-5d79-488d-a532-df7467f266c3.png">

**Comment by dylanjha** [comment]
That is ... really odd

And as a matter of fact. I can repro it. Confirmed

A hard refresh fixes it `cmd + shift + r`, might be a caching thing in the youtube iframe going on

**Comment by luwes** [comment]
I've encountered this as well in the https://github.com/muxinc/media-group project.

my fork fixes a bunch and adds some more events etc. I'll try to open a PR soon.
https://github.com/luwes/youtube-video-element

**Comment by luwes** [comment]
PR open at https://github.com/muxinc/youtube-video-element/pull/19
