### ISSUE TITLE
Thumbnails track for timeline hover preview not working when the underlying media element uses HLS.js

### ISSUE THREAD

**Issue by dylanjha** [muxinc/media-chrome#29]
```
<track label="thumbnails" default kind="metadata" src="https://image.mux.com/DS00Spx1CV902MCtPj5WknGlR102V5HFkDe/storyboard.vtt"></track>
```

This example works with an mp4 source

But in this nearly identical example with HLS instead the `thumbnailContainer` shows up, but it's not populated with thumbnails from the sprite.

**Comment by dylanjha** [comment]
Got a lead here.

Left is:

* mp4 source

Right is:

* HLS source, Hls.js attached to the `video` element with `hls.attachMedia(videoEl)`

For some reason, when using the HLS source the `media.textTracks` are there, but on the text track instance `cues` is null.

![text-track-cues_2021-05-25_17-10-20](https://user-images.githubusercontent.com/764988/119583815-3e13a000-bd7c-11eb-8d95-1bf86b5abbc9.png)

**Comment by dylanjha** [comment]
Documenting what we found here (h/t @redoPop)

## Current Bug

* On Event.MEDIA_ATTACHING the TimelineController calls this._cleanTracks [here](https://github.com/video-dev/hls.js/blob/94e4d9307a5f0c9c602831ae9454a9746a440fa3/src/controller/timeline-controller.ts#L283)
* `_cleanTracks` puts the metadata track through `clearCurrentCues` [here](https://github.com/video-dev/hls.js/blob/90321c4720147e4c69cb219e7a4e5c7fc2401987/src/controller/timeline-controller.ts#L322)
* `clearCurrentCues` puts the metadata track into a permanent disabled state (explained below)

The purpose of `clearCurrentCues` is to  remove subtitle tracks that were maybe associated with a previous video that used the same element. And this is actually a race condition and it depends at what point Hls.js gets attached

In a normal flow of things:

1.  text track starts `"disabled"`
2.  text track is loaded and switches to `"hidden"`
3. Hls.js gets attached and `clearCurrentCues` momentarily disables the track and then switches the track back to `"hidden"`

But in the broken flow:

1. text track starts `"disabled"`
2. Hls.js gets attached and `clearCurrentCues` switches to `"disabled"`
3. B/c the mode was forced to "disabled", the text track will no longer transition to `"hidden"` like it would under normal circumstances

## How to avoid:

* Flip the text track's mode to "hidden" either before or after Hls.js gets attached.

## Possible solutions:

* Figure out a fix in Hls.js? Ideally, I don't think Hls.js wants to be messing with a `metadata` text track
* Implement the workaround in `media-chrome`.

😅

**Comment by heff** [comment]
@dylanjha check out muxinc/custom-video-element#4

Seems to work. Just need to publish it through the dependency chain.
