### ISSUE TITLE
didn't work for me :/

### ISSUE THREAD

**Issue by tomByrer** [muxinc/media-chrome#3]
After having to remove the `"type": "module",` line from `package.json` [thanks to Gulp](https://stackoverflow.com/questions/60209196/gulp-throws-error-must-use-import-to-load-es-module), then firing up lite-server, I could not get any of the example files to work but the "youtube-controls".  Some didn't show any sign of a player at all, & this seems odd

![image](https://user-images.githubusercontent.com/1308419/78512855-78337400-776d-11ea-96fd-071e3b15ffc1.png)

Win10, Firefox & Chromium based browser.

**Comment by heff** [comment]
Thanks for giving it a shot! Could you help me understand how you're using gulp where this happens?

**Comment by tomByrer** [comment]
`yarn build` & `yarn dev` won't run unless I remove the `"type": "module",`.

**Comment by dylanjha** [comment]
I think I ran into this same issue:

![nextjs-media-chrome_2020-11-12_13-26-01](https://user-images.githubusercontent.com/764988/98998231-a985d680-24ea-11eb-8c3e-db7e615943ef.png)

**Comment by heff** [comment]
Switched gulp over to use es6 imports, which I think should fix this issue. @dylanjha want to try again? 🙏

**Comment by heff** [comment]
I think the issue is fixed. Please confirm if you can. Re-open if not.
