### ISSUE TITLE
YouTube Example Play Button Not Working

### ISSUE THREAD

**Issue by kik-o** [muxinc/media-chrome#325]
The play button on [YouTube Media Example](https://media-chrome.mux.dev/examples/media-elements/youtube.html) stops working intermittently. On the initial load of the page, the pause button is shown instead of the play button and clicking it does not start the video. I noticed that after refreshing the page a few times the play button would appear and things would work as expected. 

Using Chrome @ latest, macOS Monterey. Also tested on Windows 11 with same results.

https://www.loom.com/share/7ddadfd25eb646cfa6f7875e842faa7a

**Comment by cjpillsbury** [comment]
Looks like a bug in https://github.com/muxinc/youtube-video-element. Because youtube relies on an iframe that loads up asynchronously, there are some acrobatics involved under the hood on initialization. I'll open an issue there and reference this one.

**Comment by luwes** [comment]
Closing in favor of https://github.com/muxinc/media-chrome/issues/280
