### ISSUE TITLE
React controls broken in 0.12.0+

### ISSUE THREAD

**Issue by ShaunDychko** [muxinc/media-chrome#335]
[This codepen with media-chrome 0.11.1](https://codepen.io/checkmark/pen/LYmMLGj) shows a working video player with controls using React, whereas when [using media-chrome 0.12.0](https://codepen.io/checkmark/pen/rNvowPw), some of the controls are missing. The codepens are identical except for the version of media-chrome. During local development with Gatsby, I think this issue is responsible for the error message 

> Error in function createElement in ./node_modules/react-dom/cjs/react-dom.development.js:8995
Failed to construct 'CustomElement': The result must not have attributes

That error message, and the missing controls on the codepen, occur for media-chrome versions 0.12.0+, and the errors go away when using media-chrome@^0.11.

**Comment by dylanjha** [comment]
@ShaunDychko thank you for the clear bug report and repo case.

Can definitely see that something funky is going on here.

For reference when we dig into this, [here is the diff](https://github.com/muxinc/media-chrome/compare/v0.11.1...v0.12.0)

We'll do our best to get this patched. Thank you! 🙌🏼

**Comment by kasperkamperman** [comment]
I don't work with React, but I get exactly the same error when I use Media-Chrome in Svelte. 

Indeed switching to 0.11 solved this issue.

**Comment by ph4un00b** [comment]
I work on react, had this issue, installed back 
`"media-chrome": "0.11.0"` on `package.json`
and the issues are gone.

let us know when is solved.
btw, thanks for the components ╰(*°▽°*)╯, 
super cool experience.

**Comment by gkatsev** [comment]
Hey, we have a fix for this. Have the canary updated in the codepen https://codepen.io/gkatsev/pen/ExLMZPa

**Comment by gkatsev** [comment]
Should be fixed in 0.14.1!

**Comment by ph4un00b** [comment]
lovely @gkatsev I tested it out the whole day yesterday, and no problems 👌
thanks! now looking for ssr but that's another branch of stuff xp.

**Comment by gkatsev** [comment]
Yeah, ssr is a whole other 🥫🪱
