### ISSUE TITLE
Video.js player "videojs-video" error "JSX.IntrinsicElements".typescript on Next.js

### ISSUE THREAD

**Issue by donfrancisco** [muxinc/media-chrome#348]
@luwes and @heff 

When attempting to Integrate Media Chrome "videojs-video" into Next.js with Typescript I am getting the following errors:

```
`Property `videojs-video` does not exist on type `'JSX.IntrinsicElements'.typescript(2339)``
```
```
Could not find a declaration file for module 'videojs-video-element'. '/project/sandbox/node_modules/videojs-video-element/dist/videojs-video-element.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/videojs-video-element` if it exists or add a new declaration (.d.ts) file containing `declare module 'videojs-video-element';`
```

I have an example CSB with the error in the `pages/index.tsx`: [Codesandbox Next.js Example](https://codesandbox.io/p/sandbox/media-chrome-next-js-typescrypt-yeswhv?file=%2Fpages%2Findex.tsx
)

Tried to declare "videojs-video" as an "any" type in a JSX namespace in my `declarations.d.ts` file with no success.

```
declare namespace JSX {
  interface IntrinsicElements {
    "videojs-video": any;
  }
}
```

Are there examples of a Next.js working with the other players Web Component instead of just the normal **"video"** element?

Looking to use this HLS video to play `src="https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"`

```
<dash-video></dash-video>
<hls-video></hls-video>
<jwplayer-video></jwplayer-video>
<media-playlist></media-playlist>
<mux-video></mux-video>
<videojs-video></videojs-video>
<vimeo-video></vimeo-video>
<wistia-video></wistia-video>
<youtube-video></youtube-video>
```

**Comment by heff** [comment]
Sorry for the slow response on this one @donfrancisco. I'm not familiar enough with this area to understand what needs to happen. Maybe @cjpillsbury or @gkatsev can weigh in.

**Comment by luwes** [comment]
One of the solutions to this issue is posted here, custom elements have to be added to the type defs.
https://stackoverflow.com/a/57449556/268820
