### ISSUE TITLE
keyboard shortcuts use e.target but probably should use e.composedPath

### ISSUE THREAD

**Issue by gkatsev** [muxinc/media-chrome#363]
Currently, our element opt-out of hotkey handling uses `e.target` to check `keysUse` to know whether to ignore a particular key on the focused element, however, shadow-dom complicated things, so, we may want to swap to use `composedPath()`.
https://github.com/muxinc/media-chrome/blob/4d76fc07f60a2456df02f24ef7aea62c251d594b/src/js/media-controller.js#L801-L808

**Comment by heff** [comment]
I think we could probably move this to a TODO code comment in the related code here and close this issue.
