### ISSUE TITLE
Listbox followups

### ISSUE THREAD

**Issue by gkatsev** [muxinc/media-chrome#387]
- [x] a selectmenu-like menu - https://github.com/muxinc/media-chrome/pull/393
- [x] default styles for the listbox (from https://github.com/muxinc/media-chrome/pull/377#discussion_r1041606019) - https://github.com/muxinc/media-chrome/pull/399
- [x] removing a track should update the captions listbox appropriately - https://github.com/muxinc/media-chrome/pull/399
- [x] Off item for the captions listbox. Could be an option for the listbox whether to create an automatic off item or could be a captions listbox specific feature. Currently, the way to turn off an item on a listbox is to interact on the selected item. This probably is unwanted if there is an explicit Off item. (from https://github.com/muxinc/media-chrome/pull/377#discussion_r1041424407 https://github.com/muxinc/media-chrome/pull/377#pullrequestreview-1207545629) - https://github.com/muxinc/media-chrome/pull/399
- [x] have a hover style on listitems - https://github.com/muxinc/media-chrome/pull/426
- [x] keep the captions menu button within the controller bounds - https://github.com/muxinc/media-chrome/pull/426
- [ ] The captions button should toggle no captions and the previously selected track. If no previous selection was present, do the current algorithm selection of choosing the first item. See https://github.com/muxinc/media-chrome/pull/442/commits/5dbc248b108a4caeb06d59870fbec94be98a3f3c for inspiration, but should be contained to the captions button only.
- [x] rename `media-chrome-listitem` to `media-chrome-option`
- [x] make `media-chrome-listitem` more similar to `<option>` element in terms of props/attrs
  - things like `selected` attribute instead of require `aria-selected="true"`, and then we'd want to sprout the corresponding aria attr dependingly.
- [ ] make `media-chrome-listbox` more similar to `<select>`/`<selectmenu>` element in terms of props/attrs
  - things like `multiple` prop instead of requiring `aria-multiselectable="true"`
- [x] when a listbox is used in a selectmenu, clicking the option itself shouldn't deselect it
- [ ] provide a programmatic interface to the listbox so that the selected items can be changed programmatically.
- [x] consolidate MEDIA_CAPTIONS_LIST and MEDIA_SUBTITLES_LIST
- [ ] Consider choosing the captions track that matches the media-controller's lang/locale if available.
- [ ] (maybe) open on hover for captions menu
- [x] animate opening/closing of the menu
- [x] customize things like selected item by prepending a checkmark
  - might involve something like adding parts everywhere and making sure it's exported properly
- [ ] figure out disabled for captions-menu-button
- [ ] when a menu-button is disabled, it should close the menu
- [ ] Consider using [delegatesFocus](https://github.com/TakayoshiKochi/tabindex-focus-navigation-explainer/blob/master/TabindexFocusNavigationExplainer.md) for the listbox

**Comment by gkatsev** [comment]
One thing that we need to figure out is whether the captions menu-button replaces the current captions button or, I think, ideally, is an addition to it. Doing the latter might require figuring out a more full-fledged menu system, so, maybe we have it be a replacement for the captions button *right* now?

Thoughts @heff?

**Comment by heff** [comment]
> One thing that we need to figure out is whether the captions menu-button replaces the current captions button or, I think, ideally, is an addition to it. 

I think we could make it easy on ourselves and have two buttons:
* `captions-button`
* `captions-menu-button`

We can update demos/examples to use the latter when it makes sense. I at least can still see some value in a simple toggle button. And I feel like menu buttons should be named as such to be clear about their makeup and features.

**Comment by gkatsev** [comment]
I've been marking each TODO item from the top to include the appropiate PR. https://github.com/muxinc/media-chrome/pull/399 is the big chunk, but I've also just started on https://github.com/muxinc/media-chrome/pull/426 to not keep growing #399.

**Comment by heff** [comment]
I hacked the docs inline to show what I mean by "documenting control bar element styling". As we all expected, styling of direct control bar children can have a very different effect on the selectmenu component compared to every other element in the control bar.

<img width="923" alt="image" src="https://user-images.githubusercontent.com/166/227275434-b98290b8-8829-4ee4-93b5-3763b21fedb4.png">

While selectmenu is moving towards a normal thing, it's definitely not well known today, and this will be somewhere between an annoyance to a real friction point depending on the dev/designer's CSS aptitude. We should just get ahead of this as best we can with docs. I can see a styling doc/note summary of the situation and solutions that we can point back to in selectmenu-specific docs.

**Comment by luwes** [comment]
closing this issue as done. the most crucial todo items are checked off.

we can move the remaining items to discussions.
some things that we need solve are:

- the naming of our `-selectmenu` elements which is up in the air https://github.com/openui/open-ui/issues/773
- create a new popup container that can hold 2 or more selectmenu's for menu's that have speed + quality or quality + audiotracks 

there's also the little pickle of wether aria menu & co is better suited as replacement of selectmenu
https://github.com/openui/open-ui/issues/541

I still like selectmenu because it could potentially remove lots of our javascript logic in the future.
