### ISSUE TITLE
Add and publish a custom elements manifest

### ISSUE THREAD

**Issue by justinfagnani** [muxinc/media-chrome#388]
My team is working on a new web components catalog to replace the aging webcomponents.org catalog. The new catalog is based on the [Custom Elements Manifest](https://github.com/webcomponents/custom-elements-manifest) file format for describing a package of elements and their APIs, etc. To be included in the catalog a package _must_ have a valid manifest file, linked from package.json `"customElements"` field.

I think the Media Chrome elements would be an amazing addition to the catalog when it launches, and that the catalog could drive a lot of usage for high-quality elements like Media Chrome! I'm reaching out to see if you can publish a manifest so that we can make sure everything renders perfectly as we develop it.

There are tools that can help you automatically generate manifests from source with jsdoc comments, such as https://www.npmjs.com/package/@custom-elements-manifest/analyzer

**Comment by dylanjha** [comment]
Thanks @justinfagnani for bringing this to our attention! We'd love to have Media Chrome on webcomponents.org

Linking a couple related bits here:

- https://github.com/muxinc/media-chrome/discussions/158
- https://github.com/muxinc/media-chrome/pull/183

**Comment by heff** [comment]
@justinfagnani see PR #417. Does it meet the needs here?

Or @luwes is this closable?

**Comment by justinfagnani** [comment]
@heff that looks great!

Once I start running manifest though validation, I'll post any errors that brings up.

One thing to look out for is paths in the manifest. They should be pointing to where you can import elements from. Looking here: https://unpkg.com/browse/media-chrome@0.17.0/dist/custom-elements.json I'm not sure if that's the case, with the `src/` folder in there.

**Comment by luwes** [comment]
Fixed in #521
