### ISSUE TITLE
media-time-range duration discrepancy when duration is a float

### ISSUE THREAD

**Issue by reckoner165** [muxinc/media-chrome#394]
[This line](https://github.com/muxinc/media-chrome/blob/main/src/js/media-time-range.js#L235) truncates the duration value to its floor before setting the time range max. When duration value is a float, this can cause the seek position to reach the end before the video ends. In cases where `duration - Math.floor(duration) >= 0.5s`, this is creates a perceptible discrepancy between player and controlbar states. 

It would be great if the max value for the time range is rounded to the nearest 250 or 500ms instead. In this case, stepping can perhaps be set to `Math.min(currentTime + 1, duration)`?

**Comment by dylanjha** [comment]
Thanks @reckoner165 ! We might not need to do the floor anymore. I suspect that might be a relic from before this change: https://github.com/muxinc/media-chrome/pull/271

We'll have a look, thanks for opening the issue!

**Comment by luwes** [comment]
thanks for reporting Sumanth! I think I've seen this issue one time. will get a fix in soon.
