### ISSUE TITLE
Custom Web Components Not Working Properly with Media Chrome

### ISSUE THREAD

**Issue by CalculusAce** [muxinc/media-chrome#412]
I am having a hard time figuring out how to implement the documented custom web components with media chrome. I have tried the HLS and YouTube components, and both result in a cluttered media control bar with no portion of the video window visible. It seems like the video is actually being imported, because the media time display is showing the correct video length on my end, but I cannot see or play the video in any capacity. I am working in React, and the base, mux hosted sample video with the video tag is working as expected.

I initially found media chrome from a live-demo youtube video, and in that video, the same issue I am seeing was encountered. Granted they were doing the demonstration in codesandbox, so I assumed that was likely the problem at that time. As a result, I installed all the necessary dependencies into my local environment to test out media chrome, but I am still seeing the problem. I have linked the video with a timestamp below to showcase the output I am seeing as well:

https://youtu.be/qgyBMa0H2UM?t=5144

I am on the latest version of media chrome and attempted to get the youtube component working with the original component linked in the media chrome docs and with the fork luwes made of the youtube component, which I found in a different github issue. As for the HLS component, I have only tried the component mentioned in the media chrome docs. I took a look at the examples on the media chrome dev page too, and I can't find anything different about what I am doing versus those examples either.

Any advice or code that could be provided for the correct way to implement custom web components with media chrome in React would be greatly appreciated. I am not sure if this is a known issue or if there's something I am missing about how to implement these custom web components.

Thanks!

**Comment by luwes** [comment]
thanks for the feedback! I believe the issue you, Thuy and Jason were seeing is that the custom media element doesn't have any dimensions. Try adding a `display: block; width: 100%; aspect-ratio: 16/9;` to the `<youtube-video>` or `<vimeo-video>` element. did it fix the issue?

**Comment by CalculusAce** [comment]
Thanks a lot for pointing that out. I managed to get it working with the youtube component. I am still trying to figure out why the preview thumbnails aren't appearing when I hover over the time range, but I will spend some more time with it and open another issue if I can't get it working.

**Comment by luwes** [comment]
@CalculusAce the preview thumbnails will be difficult to get working.
you will need a track element like here with a `.vtt` file pointing to the preview thumbnails

https://github.com/muxinc/media-chrome/blob/main/examples/advanced.html#L42-L47

https://image.mux.com/A3VXy02VoUinw01pwyomEO3bHnG4P32xzV7u1j1FSzjNg/storyboard.vtt

**Comment by heff** [comment]
> Try adding a display: block; width: 100%; aspect-ratio: 16/9; to the <youtube-video> or <vimeo-video> element. did it fix the issue?

@luwes is there anything we can do to make this just work by default? I have a feeling people are going to keep running into this.
