### ISSUE TITLE
Fix issues related to live demo on Learn With Jason

### ISSUE THREAD

**Issue by heff** [muxinc/media-chrome#423]
The media chrome demo at the end of [Thuy's interview here](https://youtu.be/qgyBMa0H2UM?t=4704) is PAINFUL to watch. Let's identify and fix all the issues why this simple, intuitive walk-through didn't JustWork.

- [x] ~~Apparent race condition with loading the youtube player, causing a "getPlayerState is not a function" error.~~ See #280 
- [x] A jumble of controls from no default sizing for custom media elements. `<video>` has default dimensions, so should custom media emulating the video element.

Anything else I'm missing? I'm late to the game on this one, so if both of these are fixed great. Just didn't want to lose sight of them.

**Comment by cjpillsbury** [comment]
Good callout. As a starting point, let's make very basic official codesandbox examples for each media chrome + custom video element, since at least some of these issues are likely tied to codesandbox(-like) environments with hot reloading and iframes etc. etc.

**Comment by cjpillsbury** [comment]
<img width="1904" alt="Screen Shot 2023-01-09 at 3 29 14 PM" src="https://user-images.githubusercontent.com/2389566/211428719-196b4b37-1f72-4507-8081-d49771a41465.png">
looks like the first one is another "async bootstrapping" bug in youtube-element.

**Comment by luwes** [comment]
yes indeed will be nice to give some attention to these custom video elements

can we remove the first list item here and make this issue specific about the minimum dimensions for custom video elements? because that bug report has been open for a long time here https://github.com/muxinc/media-chrome/issues/280
makes a bit easier for others scanning open issues

I was about to open a PR with my improved version one of these days, that should take care of the first issue
https://github.com/luwes/youtube-video-element

**Comment by luwes** [comment]
added the refactor at https://github.com/muxinc/youtube-video-element/pull/19

**Comment by luwes** [comment]
`<youtube-video>` has a default minimum width and height now. same native video. 300px / 150px

the bug still persists 😿 
https://codesandbox.io/s/media-chrome-w-youtube-video-element-jrhhzn?file=/index.html

reason is that the slotted media gets with 100% dimensions from the media-container CSS but the `<media-controller>` element itself has no dimensions.

**Comment by luwes** [comment]
this PR should fix the collapsing issue by setting a default min-width and min-height of 300x150.
https://github.com/muxinc/youtube-video-element/pull/21

a small downside is that users will have to override those CSS props if they want the player to go below those dimensions.
