### ISSUE TITLE
Add CSS var to set the font family on media-time-display

### ISSUE THREAD

**Issue by dylanjha** [muxinc/media-chrome#453]
Seems like this is missing and it should be a thing. I don't see why it wouldn't be?

cc: @davekiss

**Comment by luwes** [comment]
We might as well change the default font while we're at it, Arial is so old school

**Comment by luwes** [comment]
a valid point against it is that the font-family is inherited from the custom element

![SCR-20230323-mk8](https://user-images.githubusercontent.com/360826/227364623-2b1d5c00-99cf-45fd-8152-f0ea5f8adeb3.png)

but it would still be handy for themes for example

**Comment by luwes** [comment]
+1 for adding a CSS var for changing the font.

Related glitch fix PR: https://github.com/muxinc/media-chrome/pull/526
Related player issue: https://github.com/muxinc/elements/discussions/654
