### ISSUE TITLE
No progress bar background initially

### ISSUE THREAD

**Issue by heff** [muxinc/media-chrome#56]
Looks like we lost a background on the main progress bar at some point. It may only happen when preload="none".

![image](https://user-images.githubusercontent.com/166/131271004-a935b287-4226-4fa4-b916-f71ad54d7423.png)

Compare /examples/standalone-controls.html

![image](https://user-images.githubusercontent.com/166/131271259-076a2300-a593-4fbe-b15d-e4aaa7da07ea.png)

to https://unpkg.com/media-chrome@0.2.2/examples/standalone-controls.html

![image](https://user-images.githubusercontent.com/166/131271266-b424141b-251c-4f55-8b94-19994ab3bd1e.png)

**Comment by bhagyamudgal** [comment]
Can I work on this issue?
