### ISSUE TITLE
Preview images appear to be broken

### ISSUE THREAD

**Issue by heff** [muxinc/media-chrome#57]
Compare main branch youtube theme

![image](https://user-images.githubusercontent.com/166/131271416-2c9da27e-ef65-4266-ba0c-c27443c09383.png)

to https://unpkg.com/media-chrome@0.2.2/examples/themes/youtube-theme.html

![image](https://user-images.githubusercontent.com/166/131271439-87767ed3-3752-4ea1-b340-c2816e20b423.png)

**Comment by cjpillsbury** [comment]
This was identified and should already be resolved in a pending branch (yet to be PR-ed based on current backlog. Thanks for filing it. I'll be sure to associate it with the branch/PR once it's ready.

**Comment by cjpillsbury** [comment]
Resolved by #62
