### ISSUE TITLE
How to tell if an iOS device is playing media chrome in Full Screen

### ISSUE THREAD

**Issue by shenders13** [muxinc/media-chrome#593]
Hi there 👋 

I noticed that the `media-is-fullscreen` attribute does not get applied to the `<media-controller>` element on iOS. It does on Desktop.

Is there a way we can programatically know whether or not the video is in fullscreen mode (that works on iOS also)?

At the moment, we read "media chrome state" from the attributes on the `<media-controller>`. The fullscreen value is incorrect on iOS, so therefore our state is incorrect.

Is there another way to read fullscreen state?

I even tried adding an event listener manually (just for iOS) but it doesn't fire when you toggle full screen 😢 

```ts
document.addEventListener("webkitfullscreenchange", function() {
  ...
});
```

### iOS - no media-is-fullscreen attribute

_*Tested using Browserstack_

<img width="800" alt="Screenshot 2023-05-10 at 1 45 39 pm" src="https://github.com/muxinc/media-chrome/assets/15011940/6ba6ea2f-28f0-48c6-a1a7-56418aed5258">

### Desktop - media-is-fullscreen attribute is present

<img width="824" alt="Screenshot 2023-05-10 at 1 46 15 pm" src="https://github.com/muxinc/media-chrome/assets/15011940/c866d617-b814-479f-b9c2-0cfe54cfc7bf">

Thanks in advance

**Comment by luwes** [comment]
thanks for opening this issue! that doesn't seem right, we'll have a look soon. I would also assume the attribute should be set

**Comment by dylanjha** [comment]
Looks like @gkatsev might have seen a similar issue on video.js a couple years ago: https://github.com/videojs/video.js/issues/6645
