### ISSUE TITLE
Missing CJS export mappings causing issues with 3rd party published CJS modules

### ISSUE THREAD

**Issue by cjpillsbury** [muxinc/media-chrome#637]
While Media Chrome provides published CJS versions of its modules for all "standard" packages, it:
1. Does not identify these in a robust way in its package.json
2. Does not do this for the react wrapper import, which is "built" using a custom node script directly in `./dist`

This causes issues for any library published that
1. has Media Chrome as a dependency
2. publishes a CJS "flavor" of the library package module(s)
3. keeps Media Chrome as an external/unbundled dependency in the published module(s)

Relates to: sanity-io/sanity-plugin-mux-input#252

**Comment by danteissaias** [comment]
I haven't closely studied the implementation of the react wrapper, but shouldn't it be possible to run it through esbuild after the ESM version has been generated by the script to get a CJS version?

**Comment by cjpillsbury** [comment]
@danteissaias we should be able to hack something in, yeah! The current react wrapper components module is produced in dist based on some detections of "registered custom elements" (by using a hacked shim of https://developer.mozilla.org/en-US/docs/Web/API/Window/customElements for detection). That said, we should be able to still run an esbuild script against it directly in dist to generate a CJS version. We'd likely still also need to add multiple entrypoints to the package.json for build setups to work as expected, and we'll want to proceed with caution since (unfortunately) different builds will make different assumptions based on these configs.

**Comment by luwes** [comment]
fixed in v1! ^^
https://publint.dev/media-chrome@1.0.0
