### ISSUE TITLE
Dave's docs feedback

### ISSUE THREAD

**Issue by luwes** [muxinc/media-chrome#649]
# Get Started

- [x] Move example up above key features
- [ ] ~Do we have an overall components list? Might be good to link to that page in the opening paragraph.~ 
  *we don't have an index page yet*
- [x] I would suggest reducing the example code by just a few LOC. The kitchen sink seems like a good idea, but it might be a little overwhelming as the first example we see.
- [x] “Slots are a feature of HTML Web Components” should link to MDN
- [ ] “You could also set the mediaController property of the element with JavaScript” could you describe an instance where this might be practical?
- [x] Move “Compatible media elements” above “Taking it further”
- [ ] Also the mix of dark codefence blocks and light sandpack editor is a little strange, would be nice to make that cohesive
  *I did a spike on this last time, it's quite difficult currently to get as granular as we want. 
  see https://github.com/shikijs/shiki/blob/main/docs/themes.md#theming-with-css-variables*

# Styling

- [x] rename to “Styling your player”
- [x] Styling with CSS variables sandpack, could we use more prominent color changes? Make it easily apparent that it is different from the first sandpack
- [x] Do we want to make a recommendation at the bottom of what the reader might want to read next?

# React usage

- [x] “Since there are still some complexities with using Web Components in React,” if I’m new to Web Components I have no idea what this means, is there any additional reading we can link to on this?
- [x] “Additionally, we’ll automatically translate “special” React attributes like [className](<https://reactjs.org/docs/dom-elements.html#classname>).” does the reader need to know this, or should it just work? className isn’t special if I am a React user, it is just part of React, so I might read this and get a little confused as to what is meant here.
- [x] Property Values same as above, shouldn’t this just work?
I might suggest consolidating some of the sections that describe how we passthru your other props into a single sentence

# Prevent layout shift

- [x] “Cumulative Layout Shift is when content on your page shifts.” add a sentence describing the impact of this — how it can be jarring for site visitors to lose track of what they were looking at or reading as the page loads, or something similar to this
- [x] “Video players are notorious for causing CLS.” Let’s answer the “why” here — “since we don’t know the dimensions/content of the media file until it is loaded” or something similar
- [ ] Maybe we can add a visualization for this somehow? A before/after of a video loading without aspect-ratio and then one with aspect-ratio

# Keyboard shortcuts

- [x] Remove duplicate “Keyboard Shortcuts” subheading
- [x] It’s a little funny seeing emoji appear in the keyboard shortcut, should we instead just list “Right arrow” and “Left arrow”? ArrowLeft and ArrowRight?
- [x] “If you are implementing an interactive element that uses any of these keys, you can stopPropagation in your keyup handler.” Mark stopPropagation as code
- [x] Make hotkeys property an h2
- [ ] Can we describe hotkeys a little more? I don’t really understand what this is used for or why it is different from what was described in the rest of the guide

# Audio player 

- [x] Add some context going into this guide. “While most of our examples have shown how to use Media Chrome for video playback, it’s just as practical to use it to build an audio player as well.”
- [x] “Since audio players don’t use the same visual layout as video players do, we can present a much simpler UI to the user. You can use the audio attribute to strip away the unused standard [positioning slots](https://media-chrome-docs-git-fork-cjpillsbury-docs-0x-1x-mi-d37eb4-mux.vercel.app/en/position-controls) from your player”
- [ ] It’d be cool to have a styled audio player example here

# Media elements

- [x] I feel like we could have an overview page for media elements as their documented use feels a little sparse. As far as I can tell, the only mention we have of how they work is a paragraph at the bottom of the get started guide.
- [ ] Maybe there’s room to have some info on how to build one of these for compatibility with the user’s preferred provider?

# Themes

- [ ] For themes, do we want to move the CSB's to sandpack?

# General docs

- [ ] Should sidebar items be collapsed to cleanup the clutter a bit?
- [ ] Maybe the Secondary sidebar should highlight the active section
- [ ] Sandpack feels like it might do better with a border showing that it is a “widget” that the user can interact with

# Showcase 

- [ ] Are there more examples we can show here? This feels like a huge opportunity to show off the things you can achieve with media-chrome
- [ ] If we can add to the list, perhaps we should have a showcase grid or gallery that looks a little cleaner for browsing designs for inspiration
I would also link to this in the "Get started" guide once we have more examples

**Comment by heff** [comment]
@luwes Looks like you've made a lot of progress on this one. What's the update? Is it worth breaking any of these out into their own issue if we're not going to get to it soon?

**Comment by luwes** [comment]
I think it can be closed for now.
