### ISSUE TITLE
Time range drag doesn't move current time on iOS

### ISSUE THREAD

**Issue by flipnow** [muxinc/media-chrome#662]
Steps to reproduce:

1. Open https://4rv092.csb.app/ on iOS safari
2. Try to drag time range but not by input thumb

Actual result:

Dragging only changes preview time but not current time.

Expected result:

I am not entirely sure if it's expected or maybe just a quirk of iOS system but it's definitely not consistent with other platforms. On any desktop browser or even Android Chrome dragging on time range (not by thumb indicator) does move current time to correct position.

Why is this an issue:

On smaller iPhone screens if user doesn't hit precisely the input thumb drag will have no effect which can cause a lot frustration.

**Comment by heff** [comment]
> dragging on time range (not by thumb indicator) does move current time to correct position

I think there's more of bug here. When you tap on the bar (not the handle) it seeks to that time, but touchstart+touchmove (drag without the handle) does not update the time. That's not right so labeling as a bug. Some digging is needed to understand why the touch events aren't working as expected here.

**Comment by luwes** [comment]
Thanks for the feedback! This is resolved in https://github.com/muxinc/media-chrome/releases/tag/v1.5.0
