### ISSUE TITLE
Focus Styles Inconsistent across browsers

### ISSUE THREAD

**Issue by cjpillsbury** [muxinc/media-chrome#67]
The focus styling for buttons currently looks different for different browsers:

### Chrome/"Edgeium":
<img width="812" alt="Focus (Button) - Chrome   Edgeium" src="https://user-images.githubusercontent.com/2389566/134033788-caf03446-5afc-4322-9631-3723a40c13a7.png">

### Firefox:
<img width="788" alt="Focus (Button) - Firefox" src="https://user-images.githubusercontent.com/2389566/134033795-c515a36f-2037-4de8-9e7e-c1eb28e9267f.png">

### Safari:
<img width="737" alt="Focus (Button) - Safari" src="https://user-images.githubusercontent.com/2389566/134033800-48982b9a-5813-4123-abbb-eb44cf4dc2f7.png">

**Comment by luwes** [comment]
@gkatsev was this fixed in https://github.com/muxinc/media-chrome/pull/240?

**Comment by gkatsev** [comment]
It's definitely been fixed since this issue was opened. #240 is the final piece of it. I think it started with #30, actually.

**Comment by gkatsev** [comment]
The outlines look as consistent as possible across those 3 to me right now. (Aside from the inconsistencies with focusing on media-chrome-range elements).
