### ISSUE TITLE
Replace Deprecated Webkit Fullscreen API Calls

### ISSUE THREAD

**Issue by zacswolf** [muxinc/media-chrome#673]
## Issue Description

While reviewing the codebase, I identified that the deprecated fullscreen API calls, `webkitSupportsFullscreen` and `webkitDisplayingFullscreen`, are being used. 

- `webkitSupportsFullscreen` is referenced in `src/js/utils/platform-tests.js` ([permalink](https://github.com/muxinc/media-chrome/blob/6e17284c23609048aa67f2bfa6e1fce240e7bf56/src/js/utils/platform-tests.js#L54))
- `webkitDisplayingFullscreen` is called in `src/js/controller.js` ([permalink](https://github.com/muxinc/media-chrome/blob/6e17284c23609048aa67f2bfa6e1fce240e7bf56/src/js/controller.js#L313))

## Proposed Solution

As per the [Fullscreen API documentation](https://developer.mozilla.org/en-US/docs/Web/API/Fullscreen_API#browser_compatibility), these deprecated methods can be replaced with `Document.fullscreenEnabled` and `Document.fullscreenElement` respectively. 

- Replace `HTMLVideoElement.webkitSupportsFullscreen` with `Document.fullscreenEnabled`
- Replace `HTMLVideoElement.webkitDisplayingFullscreen` with `Document.fullscreenElement`

This change aligns with the latest web standards and should not break any existing functionality.

## Steps to Reproduce (if applicable)

This issue can be observed in the codebase. It does not currently produce any runtime error, but might cause issues in the future as these deprecated calls may be removed in future versions of browsers.

**Comment by luwes** [comment]
thanks for the idea @zacswolf !

sadly I think it's still not supported on iOS Safari. iPhone is kinda special in that it only lets the video element itself go fullscreen, not other html elements. And with that the webkit specific API's have to be used on the media element itself.

let me know if you could get it working on iOS but last time I checked it didn't seem to work.

![SCR-20230623-jep](https://github.com/muxinc/media-chrome/assets/360826/e04ea32e-b3ad-4d51-8603-1b7427ed339f)
