### ISSUE TITLE
durationOnly option for <MediaTimeRange>?

### ISSUE THREAD

**Issue by simonhrogers** [muxinc/media-chrome#681]
Hi, 

It would be extremely helpful to have a durationOnly option as the current setup of MediaTimeRange doesn’t offer any typographic or layout flexibility. Is that something that could be done in a future release? 

For now I can make a workaround but obviously it’s a bit complicated for something that could be so trivial. 

Thanks,

Simon

**Comment by heff** [comment]
Hi! Can you give a little more detail on what you're trying to do? Maybe a screenshot of the design? I'm not totally clear what you mean by typographic or layout functionality.

There's a [duration display](https://www.media-chrome.org/docs/en/components/media-duration-display) component if that solves your need.

**Comment by simonhrogers** [comment]
Thanks @heff! Yes of course – so one example is this design below, where the client wishes for the start and end times to be separated by the scrubber:

<img width="1487" alt="Screenshot 2023-07-20 at 11 05 56" src="https://github.com/muxinc/media-chrome/assets/12583581/d13607b3-6243-429c-8147-e8f17f037e34">

Or another example would be if I didn’t want to use a slash to separate the times – perhaps if I wanted to use a custom glyph, or more likely – to control the precise spacing between the numerals and the slash e.g. with en-spaces, hair-spaces or another html entity which might be contained in the font. Currently this wouldn’t be possible as the duration display outputs just `0:00 / 3:33` or `0:00` only with no option to control time/duration separately. 

For example to create the example above (probably quite a clumsy solution knowing me, but it works), I’ve done the following:

```
import { useRef, useState, useEffect } from 'react'
import MuxVideo from '@mux/mux-video-react'

import {
  MediaController,
  MediaControlBar,
  MediaTimeRange,
  MediaTimeDisplay,
  MediaVolumeRange,
  MediaPlayButton,
  MediaMuteButton,
} from 'media-chrome/react'

import styles from './ProjectPageSlideshowMediaWrapperVideo.module.scss'

export interface VideoProps {
  title: string
  slug: string
  video: any
  index: number
  activeImageIndex: number
}

const primaryColor = 'white';
const chromeStyles = {
  '--media-icon-color': primaryColor,
  '--media-range-thumb-background': primaryColor,
  '--media-range-bar-color': primaryColor,
  '--media-range-track-height': '2px',
  '--media-range-thumb-height': '1.333em',
  '--media-range-thumb-width': '1.333em',
  '--media-font-family': '"Nora", serif',
  '--media-font-size': '0.75em',
  '--media-control-height': '1.5em',
  color: primaryColor,
  width: '100%',
}

export default function Video(props: VideoProps) {

  const { title, slug, video, index, activeImageIndex } = props  

  const formatDuration = (duration) => {
    const hours = Math.floor(duration / 3600)
    const minutes = Math.floor((duration % 3600) / 60)
    const seconds = Math.floor(duration % 60)
  
    const formattedHours = hours > 0 ? hours.toString() + ':' : ''
    const formattedMinutes = minutes.toString()
    const formattedSeconds = seconds.toString().padStart(2, '0')
  
    return `${formattedHours}${formattedMinutes}:${formattedSeconds}`
  }

  return (
    <MediaController
      style={chromeStyles}
    >
      <MuxVideo
        className={styles.video}
        id={`video-${slug}`}
        style={{ width: '100%', backgroundColor: 'var(--background-color)' }}
        playbackId={video.asset.playbackId}
        slot="media"
        poster={`https://image.mux.com/${video.asset.playbackId}/thumbnail.jpg?thumbtime=${video.asset.thumbTime}`}
        metadata={{
          video_id: slug,
          video_title: title,
        }}
        streamType="on-demand"
        controls={false}
      />
      <MediaControlBar>
        <MediaPlayButton></MediaPlayButton>
        <MediaTimeDisplay disabled notoggle></MediaTimeDisplay>
        <MediaTimeRange></MediaTimeRange>
        <div className={styles.mediaTimeRangeProxy}>{formatDuration(video.asset.data.duration)}</div>
        <MediaMuteButton></MediaMuteButton>
      </MediaControlBar>
    </MediaController>
  )
}
```

Thanks so much for giving this your attention so far,

Simon

**Comment by heff** [comment]
You can create the first example [using the media-time-display component](https://codepen.io/heff/pen/vYQzmYm).

For the second example you can use the media-text-display element as the spacer between the media-time-range and the media-duration-display. ([also shown here](https://codepen.io/heff/pen/vYQzmYm)).

Make sense? Does that solve it?

**Comment by simonhrogers** [comment]
Ah sorry thank you @heff :-) 

I should have caught that. `<media-duration-display>` doesn’t show up in the Algolia search results on the docs, I’m not sure if that’s why I missed it.
