### ISSUE TITLE
set breakpoint attributes quicker again

### ISSUE THREAD

**Issue by luwes** [muxinc/media-chrome#697]
https://github.com/muxinc/media-chrome/pull/682 added a delay to setting these attributes

in themes these attributes are used to trigger render and Mux player uses the breakpoints to conditionally render size based views.
as a result this delay adds a delay to render the view in Mux player and this is noticeable on player load.

some examples: 

- https://elements-demo-nextjs.vercel.app/MuxPlayer
- https://dev.playerx.io/demo/mux/

try refreshing a couple of times and you can see the jumping of control bar

**Comment by heff** [comment]
I see  a small resize of the controls on reload but nothing signifiant. Is that what we're talking about?

Do we have any sense of why there's an issue with setTimeout compared to microTask?

**Comment by luwes** [comment]
yes, it's the small resize. it's small but worth fixing I think.

yes, lowering the timeout would probably cause that resizeobserver exceeded error / warning again.

fix should be really easy, we can add those attributes 1 time "instantly" and subsequent ones will be handled by the resize observer callback...

**Comment by heff** [comment]
Ok that generally makes sense. Should be good to prioritize.
