### ISSUE TITLE
Detached HTMLVideoElements leaks when used with react

### ISSUE THREAD

**Issue by HermanBilous** [muxinc/media-chrome#750]
Steps to reproduce:
1. Modify examples/nextjs-with-typescript/pages/index.tsx by adding a button that mounts and unmounts <MediaController /> e.g:
```typescript
const [mounted, setMounted] = useState(false);
return (
....
      <button onClick={() => setMounted(prev => !prev)}>
          {mounted ? "Unmount": "Mount"}
      </button>
      {mounted && (<MediaController />)}
....
```
2. Run example and open it in chrome.
3. Click on button a few times to mount and unmount controller
4. Create memory snapshot with devtools memory tab. Search for "video" in class filter

Actual result:
Observe a list that looks like this
![image](https://github.com/muxinc/media-chrome/assets/10484970/839dcbca-a641-4cd8-9651-32dde5fbbebe)

Note: number of Detached HTMLVideoElements will be equal to number of times "unmount" is clicked + 1.

Expected result:
Only one Detached HTMLVideoElement is present in snapshots. Clicking on button won't change the number of Detached HTMLVideoElements.

**Comment by luwes** [comment]
thanks for reporting this! we will investigate

**Comment by dylanjha** [comment]
Double thank you @HermanBilous for the easy to repro report of this memory leak
