### ISSUE TITLE
mediaisfullscreen attribute not correct upon initialization

### ISSUE THREAD

**Issue by brandonhub** [muxinc/media-chrome#761]
Hey Media Chrome team!

I'm using the React distribution of Media Chrome. I noticed that upon initializing my video, the `mediaisfullscreen` attribute is set on the `MediaController`  even though the video is **not** fullscreen.  I have to toggle fullscreen on and then off to get it to the attribute to disappear.

Here is a codepen illustrating the issue: https://codesandbox.io/s/media-chrome-fullscreen-bug-35wj82

**Comment by dylanjha** [comment]
Thanks @brandonhub -- that seems to be a bug. Not sure exactly why but when we get bandwidth we'll take a closer look
