### ISSUE TITLE
Navigation not working on mobile

### ISSUE THREAD

**Issue by nilsandresen** [muxinc/media-chrome#772]
If I try to open the navigation on mobile, either on safari or on chrome with the size of a mobile device, I can't open the navigation.

![image](https://github.com/muxinc/media-chrome/assets/32036474/94543fbd-bf28-411a-a29e-a7d8000e1f6d)

**Comment by heff** [comment]
Oh boy, can confirm the hamburger nav doesn't work at the mobile size. Thanks for the heads up @nilsandresen!

@luwes any quick thoughts on what might be causing that?
