### ISSUE TITLE
How to get error messages

### ISSUE THREAD

**Issue by jffluis** [muxinc/media-chrome#776]
Hi. I'm running into an issue that some of my video link are broken an need to alert the user that video is returning 404.
There is an API for that?

Thank you.

**Comment by luwes** [comment]
Thanks for the feedback! 

Error dialogs are not included in the library yet but they can be added manually with listening to the video error event and showing an overlay with the message of `video.error`.

See https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/error_event

**Comment by jffluis** [comment]
ty just found a way to do it.
