### ISSUE TITLE
Slack Invite Link is Broken

### ISSUE THREAD

**Issue by jelias** [muxinc/media-chrome#786]
Hello, I was trying to jump on the slack channel to ask a question and cannot seem to join...

Will create a new issue here for my actual problem, but would much prefer to chat with someone!

**Comment by luwes** [comment]
Hi! thanks for reaching out, does the Slack signup show an error or show a response?
The link seems to work https://video-dev.fly.dev/

**Comment by jelias** [comment]
Upon clicking join, I am redirect to this:
![CleanShot 2024-01-15 at 11 16 12](https://github.com/muxinc/media-chrome/assets/1644531/916355e3-0c0f-41b1-b899-347f5531b49c)

**Comment by heff** [comment]
Fixed! Thanks for the callout.
