### ISSUE TITLE
DOMException: Failed to execute 'cancelWatchAvailability' on 'RemotePlayback'

### ISSUE THREAD

**Issue by clemator** [muxinc/media-chrome#854]
Related to #809 

Vue: 3.4.19
Media-chrome: 3.X

## Observed behavior
Hello 👋 

We have a console error whenever we unmount the media chrome wrapped video player.
This only happens when the video tag within has the `disableRemotePlayback` attribute.

## Expected behavior
We should unmount the component without having an error

## Steps:
Go to https://stackblitz.com/edit/vitejs-vite-ufbrz6?file=src%2FApp.vue
Open the console
Click on toggle button
You will see the error pop in the console

![Capture d’écran 2024-03-13 à 17 36 33](https://github.com/muxinc/media-chrome/assets/6240835/578f8c37-44de-4b6a-8925-c84ccfb4b6d6)

**Comment by cjpillsbury** [comment]
Hey @clemator thanks for both the feedback and the repro code! This shouldn't cause an issues, but we can certainly up that case to minimally catch the Promise & swallow the error or similar.
