### ISSUE TITLE
Default of current-time-display is broken

### ISSUE THREAD

**Issue by heff** [muxinc/media-chrome#88]
Follow up on #74 

The same is true for other time-display elements.

Before #74
![image](https://user-images.githubusercontent.com/166/139512012-07f48f35-d3c0-48f6-9412-e276e1fedbb3.png)
https://media-chrome-djevl3pei-mux.vercel.app/examples/control-elements/media-current-time-display.html

After
![image](https://user-images.githubusercontent.com/166/139512166-229d9491-6a4b-4ec4-ae24-1a9b7b6aa01b.png)
https://media-chrome-err0093s8-mux.vercel.app/examples/control-elements/media-current-time-display.html

**Comment by cjpillsbury** [comment]
Unrelated to #74 . See: https://media-chrome.mux.dev/examples/control-elements/media-time-display.html
Still good as a followup if we want to re-introduce default values (consideration: `-:--` or similar instead to make clear that no value has been set?)

**Comment by heff** [comment]
Hmm, not sure where we lost that default then. But yeah, we should fix that. I like `-:--`.

**Comment by luwes** [comment]
Just checked, this is still a bug
