### ISSUE TITLE
hls-video not working on Safari iOS 16.4 - Blacked out image

### ISSUE THREAD

**Issue by xalunda** [muxinc/media-chrome#924]
Hello,

I recently implemented media-chrome as my HLS player.

I found that on iOS 16.4, sound is working, but video is blacked out.

You can reproduce on Simulator 16.4 on the examples pages
https://media-chrome.mux.dev/examples/vanilla/media-elements/hls.html

Seems to be working fine on iOS 17+

https://github.com/muxinc/media-chrome/assets/2316221/c96bd1af-102a-4562-9604-fcd14f65cd35

https://github.com/muxinc/media-chrome/assets/2316221/51dde597-f8fe-4764-9daf-02297243a50b

**Comment by luwes** [comment]
closing in favor of https://github.com/muxinc/media-elements/issues/29
