### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'updateXOffset')

### ISSUE THREAD

**Issue by rafzan** [muxinc/media-chrome#986]
I'm getting this error on Sentry, running an App on Next.js, everything is up-to-date.

Triggered on this line:
https://github.com/muxinc/media-chrome/blob/78c303221439b097eb4c2ffffc3fefd25b5e9722/src/js/media-chrome-button.ts#L324

Sampling:
55% Chrome Mobile WebView 117.0.5938 
14% Chrome Mobile 128.0.0
10% Mobile Safari 17.6
3% Chrome Mobile 129.0.0

I don't have replay sessions, but it seems this code chunk is called when the component is being unloaded.

**Comment by luwes** [comment]
thanks for reporting! is this the latest version of Media Chrome?
