### ISSUE TITLE
Uncaught exception when using <youtube-video>

### ISSUE THREAD

**Issue by limdauto** [muxinc/media-chrome#99]
Hello, I'm trying out media-chrome with `<youtube-video>` element as suggested in your doc and the [example](https://github.com/muxinc/media-chrome/blob/main/examples/media-elements/youtube.html) I found. My code is simply:

```html
<script type="module" src="https://unpkg.com/youtube-video-element@0"></script>
<script type="module" src="https://unpkg.com/media-chrome@0.2"></script>
...
<media-controller>
    <youtube-video slot="media" src="https://www.youtube.com/watch?v=rubNgGj3pYo"></youtube-video>
</media-controller>
```

This is the exception I encounter:
![Screenshot from 2021-12-21 18-56-43](https://user-images.githubusercontent.com/2032984/146992651-ff909a3e-acd8-40af-8985-392bc645e98f.png)

Happy to provide more details to help debugging!

**Comment by luwes** [comment]
@limdauto thanks for the feedback, there was indeed a race condition bug in the youtube-video-element package.
It's resolved in the latest releases. 

Here's an example https://stackblitz.com/edit/media-chrome-youtube-video?file=index.html

Please let me know if you have any questions or something is not working.
